image:
  repository: 690944315170.dkr.ecr.us-west-2.amazonaws.com/go_stream
  tag: latest
  pullPolicy: Always

replicaCount: 1

# Injected into ConfigMap
env:
  ACCOUNT: ${ACCOUNT}
  DATABASE: ${DATABASE}
  SCHEMA: ${SCHEMA}
  PIPE: ${PIPE}
  PAT: ${PAT}
  
container:
  eps: 4000
  batch: 1000
  count: 0
  buffer: 1000

resources:
  limits:
    cpu: 4000m
    memory: 8000Mi
  requests:
    cpu: 4000m
    memory: 8000Mi

serviceAccount:
  create: true
  name: ""

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: NodeType
              operator: In
              values:
                - ssv2test

